HeroBoard.MVC.UI/Controllers/AssignmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HeroBoard.DATA.EF;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json.Linq;
using System.Collections;

namespace HeroBoard.MVC.UI.Controllers
{
    [Authorize]
    public class AssignmentsController : Controller
    {
        private Entities db = new Entities();

        // GET: Assignments
        [Authorize(Roles = "Admin, Manager, Hero")]
        public ActionResult Index()
        {
            string currentUserID = User.Identity.GetUserId();
            var assignments = db.Assignments.Include(a => a.AspNetUser).Include(a => a.Hero).Include(a => a.Location).Include(a => a.OpenAssignment).Include(a => a.SkillLevel);
            if (User.IsInRole("Manager"))
            {
                return View(assignments.ToList().Where(a => a.ManagerID == currentUserID));

            }
            return View(assignments.ToList().Where(o => o.Hero.UserID == currentUserID));
        }

        // GET: Assignments/Details/5
        [Authorize(Roles = "Admin, Manager, Hero")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Assignment assignment = db.Assignments.Find(id);
            if (assignment == null)
            {
                return HttpNotFound();
            }
            return View(assignment);
        }

        // GET: Assignments/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.ManagerID = new SelectList(db.AspNetUsers, "Id", "FirstName");
            ViewBag.HeroID = new SelectList(db.Heroes, "HeroID", "UserID");
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "City");
            ViewBag.OpenAssignID = new SelectList(db.OpenAssignments, "OpenAssignmentID", "ManagerID");
            ViewBag.SkillID = new SelectList(db.SkillLevels, "SkillID", "SkillName");
            return View();
        }

        // POST: Assignments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "AssignmentID,HeroID,ManagerID,LocationID,Description,SkillID,OpenAssignID,IsActive")] Assignment assignment)
        {
            if (ModelState.IsValid)
            {
                db.Assignments.Add(assignment);
                //OpenAssignment openA = new OpenAssignment();
                //openA.LocationID = assignment.LocationID;
                //openA.ManagerID = assignment.ManagerID;
                //openA.Description = assignment.Description;
                //openA.SkillID = assignment.SkillID;
                //db.OpenAssignments.Add(openA);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ManagerID = new SelectList(db.AspNetUsers, "Id", "FirstName", assignment.ManagerID);
            ViewBag.HeroID = new SelectList(db.Heroes, "HeroID", "UserID", assignment.HeroID);
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "City", assignment.LocationID);
            ViewBag.OpenAssignID = new SelectList(db.OpenAssignments, "OpenAssignID", "ManagerID", assignment.OpenAssignID);
            ViewBag.SkillID = new SelectList(db.SkillLevels, "SkillID", "SkillName", assignment.SkillID);
            return View(assignment);
        }
        [Authorize(Roles ="Hero")]
        public ActionResult Complete(int? id)
        {
            Assignment assign = db.Assignments.Find(id);
            string currentUserID = User.Identity.GetUserId();
            //AspNetUser currentUser = db.AspNetUsers.Find(currentUserID);
            var hero = db.Heroes.Where(a => a.UserID == currentUserID).FirstOrDefault();
            assign.IsActive = false;
            hero.Achievements++;
            var value = db.SkillLevels.Where(d => d.SkillID == hero.SkillLevel.SkillID +1).FirstOrDefault();
            if (hero.Achievements >= value.SkillValue)
            {
                hero.SkillID++;
                Session["Message"] = "You've achieved the Skill Level of " + hero.SkillLevel + "!";
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Assignments/Edit/5
        [Authorize(Roles = "Admin, Manager")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Assignment assignment = db.Assignments.Find(id);
            if (assignment == null)
            {
                return HttpNotFound();
            }
            ViewBag.ManagerID = new SelectList(db.AspNetUsers, "Id", "FirstName", assignment.ManagerID);
            ViewBag.HeroID = new SelectList(db.Heroes, "HeroID", "UserID", assignment.HeroID);
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "City", assignment.LocationID);
            ViewBag.OpenAssignID = new SelectList(db.OpenAssignments, "OpenAssignID", "ManagerID", assignment.OpenAssignID);
            ViewBag.SkillID = new SelectList(db.SkillLevels, "SkillID", "SkillName", assignment.SkillID);
            return View(assignment);
        }

        // POST: Assignments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager")]
        public ActionResult Edit([Bind(Include = "AssignmentID,HeroID,ManagerID,LocationID,Description,SkillID,OpenAssignID,IsActive")] Assignment assignment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(assignment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ManagerID = new SelectList(db.AspNetUsers, "Id", "FirstName", assignment.ManagerID);
            ViewBag.HeroID = new SelectList(db.Heroes, "HeroID", "UserID", assignment.HeroID);
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "City", assignment.LocationID);
            ViewBag.OpenAssignID = new SelectList(db.OpenAssignments, "OpenAssignID", "ManagerID", assignment.OpenAssignID);
            ViewBag.SkillID = new SelectList(db.SkillLevels, "SkillID", "SkillName", assignment.SkillID);
            return View(assignment);
        }

        // GET: Assignments/Delete/5
        [Authorize(Roles = "Admin, Manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Assignment assignment = db.Assignments.Find(id);
            if (assignment == null)
            {
                return HttpNotFound();
            }
            return View(assignment);
        }

        // POST: Assignments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager")]
        public ActionResult DeleteConfirmed(int id)
        {
            Assignment assignment = db.Assignments.Find(id);
            db.Assignments.Remove(assignment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HeroBoard.MVC.UI/Views/Assignments/Create.cshtml
@model HeroBoard.DATA.EF.Assignment

@if (User.IsInRole("Admin"))
{
    ViewBag.Title = "Create";

    <div class="content-md">
        <h2 class="margin-t-40 margin-l-50p">Create</h2>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4 class="margin-t-40 margin-l-50p">Assignment</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.HeroID, "HeroID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("HeroID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.HeroID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ManagerID, "ManagerID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ManagerID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ManagerID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.LocationID, "LocationID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("LocationID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SkillID, "SkillID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("SkillID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.SkillID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.OpenAssignID, "OpenAssignID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("OpenAssignID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.OpenAssignID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsActive)
                            @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>

}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HeroBoard.MVC.UI/Views/Assignments/Delete.cshtml
@model HeroBoard.DATA.EF.Assignment

@if (User.IsInRole("Admin") || User.IsInRole("Manager"))
{
    ViewBag.Title = "Delete";

    <div class="content-md">
        <h2 class="margin-t-40 margin-l-50p">@ViewBag.Title</h2>

        <h3 class="margin-t-40 margin-l-25p">Are you sure you want to delete this?</h3>
        <div>
            <h4 class="margin-t-40 margin-l-25p">Assignment</h4>
            <hr />
            <dl class="dl-horizontal margin-l-15p">
                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IsActive)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IsActive)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.AspNetUser.FirstName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.AspNetUser.FirstName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Hero.UserID)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Hero.UserID)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Location.City)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Location.City)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.OpenAssignment.ManagerID)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.OpenAssignment.ManagerID)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.SkillLevel.SkillName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SkillLevel.SkillName)
                </dd>

            </dl>

            <div class="margin-l-15p">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-actions no-color">
                        <input type="submit" value="Delete" class="btn btn-default" /> |
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                }
            </div>
        </div>
    </div>
}

HeroBoard.MVC.UI/Views/Assignments/Details.cshtml
@model HeroBoard.DATA.EF.Assignment

@if (!User.IsInRole("User"))
{
    ViewBag.Title = "Details";


    <h2>Details</h2>

    <div>
        <h4>Assignment</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Description)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Description)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AspNetUser.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AspNetUser.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Hero.UserID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Hero.UserID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Location.City)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Location.City)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OpenAssignment.ManagerID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OpenAssignment.ManagerID)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.SkillLevel.SkillName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.SkillLevel.SkillName)
            </dd>

        </dl>
    </div>
    <p>
        @if (!User.IsInRole("Hero"))
        {
            @Html.ActionLink("Edit", "Edit", new { id = Model.AssignmentID }) @:|
        }
        @Html.ActionLink("Back to List", "Index")
    </p>
}

HeroBoard.MVC.UI/Views/Assignments/Edit.cshtml
@model HeroBoard.DATA.EF.Assignment

@if (!User.IsInRole("User") && !User.IsInRole("Hero"))
{
    ViewBag.Title = "Edit";

    <h2>Edit</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Assignment</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.AssignmentID)

            <div class="form-group">
                @Html.LabelFor(model => model.HeroID, "HeroID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("HeroID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.HeroID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ManagerID, "ManagerID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("ManagerID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ManagerID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LocationID, "LocationID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("LocationID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SkillID, "SkillID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SkillID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SkillID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.OpenAssignID, "OpenAssignID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("OpenAssignID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.OpenAssignID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsActive)
                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HeroBoard.MVC.UI/Views/Assignments/Index.cshtml
@model IEnumerable<HeroBoard.DATA.EF.Assignment>

@if(!User.IsInRole("User"))
{
    ViewBag.Title = "Current Assignments";

<div class="content-md">
    <h2 class="margin-t-40 margin-l-50p">@ViewBag.Title</h2>
    <h3 class="margin-t-40 margin-l-50p">@Session["Message"]</h3>
    @if (User.IsInRole("Admin"))
    {  
    <p class="margin-t-40 margin-l-50p">
            @Html.ActionLink("New Assignment", "Create")
        </p>
    }
    <table class="table margin-l-auto margin-r-auto">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                Activity Status
            </th>
            <th>
                Manager Name
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SkillLevel.SkillName)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @if (item.IsActive == true)
                    {
                     <p>In Progress</p>
                    }
                    @if (item.IsActive == false)
                    {
                        <p>Completed</p>

                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AspNetUser.FirstName)
                    @Html.DisplayFor(modelItem => item.AspNetUser.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SkillLevel.SkillName)
                </td>
                <td>
                    @if (User.IsInRole("Hero") && item.IsActive == true)
                    {
                        using (Html.BeginForm("Complete", "Assignments", new { @id = @item.AssignmentID }))
                        {

                            <input type="submit" value="Complete" class="btn btn-success" />
                        }

                    }
                    @if (!User.IsInRole("Hero"))
                    {                  
                    @Html.ActionLink("Edit", "Edit", new { id = item.AssignmentID }) @:|
                    @Html.ActionLink("Details", "Details", new { id = item.AssignmentID }) @:|
                    @Html.ActionLink("Delete", "Delete", new { id = item.AssignmentID })
                    }
                </td>
            </tr>
        }

    </table>
</div>
}