HeroBoard.MVC.UI/Controllers/HeroesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HeroBoard.DATA.EF;
using Microsoft.AspNet.Identity.Owin;
using HeroBoard.MVC.UI.Models;
using Microsoft.AspNet.Identity;
using System.IO;

namespace HeroBoard.MVC.UI.Controllers
{
    [Authorize]
    public class HeroesController : Controller
    {
        private Entities db = new Entities();

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Heroes
        [AllowAnonymous]
        public ActionResult Index()
        {
            var heroes = db.Heroes.Include(h => h.AspNetUser).Include(h => h.Location).Include(h => h.SkillLevel);
            return View(heroes.ToList());
        }

        // GET: Heroes/Details/5
        [Authorize(Roles = "Manager, Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hero hero = db.Heroes.Find(id);
            if (hero == null)
            {
                return HttpNotFound();
            }
            return View(hero);
        }

        // GET: Heroes/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "FirstName");
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "City");
            ViewBag.SkillID = new SelectList(db.SkillLevels, "SkillID", "SkillName");
            return View();
        }

        // POST: Heroes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "HeroID,UserID,Alias,FirstName,LastName,Description,IsActive,SkillID,LocationID,ImageFileName")] Hero hero)
        {
            if (ModelState.IsValid)
            {
                db.Heroes.Add(hero);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "FirstName", hero.UserID);
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "City", hero.LocationID);
            ViewBag.SkillID = new SelectList(db.SkillLevels, "SkillID", "SkillName", hero.SkillID);
            return View(hero);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager")]
        public ActionResult HeroApplication(int? id, bool? b)
        {
            Application app = db.Applications.Find(id);
            Hero hero = new Hero();
            AspNetUser user = db.AspNetUsers.Find(app.UserId);
            app.IsDeclined = b;
            if (app.IsDeclined == false)
            {
                hero.Alias = "No Alias";
                hero.UserID = app.UserId;
                hero.FirstName = app.AspNetUser.FirstName;
                hero.LastName = app.AspNetUser.LastName;
                hero.Description = app.ManagerNotes;
                hero.ImageFileName = "noPhoto.png";
                hero.IsActive = true;
                hero.LocationID = app.OpenPosition.LocationID;
                hero.SkillID = 1;
                hero.Achievements = 0;
                if (ModelState.IsValid)
                {
                    var userManager = System.Web.HttpContext.
                        Current.GetOwinContext().GetUserManager<ApplicationUserManager>();
                    var roleAdd = UserManager.AddToRole(user.Id, "Hero");
                    var roleRem = UserManager.RemoveFromRole(user.Id, "User");

                    db.Heroes.Add(hero);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "FirstName", hero.UserID);
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "City", hero.LocationID);
            ViewBag.SkillID = new SelectList(db.SkillLevels, "SkillID", "SkillName", hero.SkillID);
            return View(hero);
        }

        // GET: Heroes/Edit/5
        [Authorize(Roles = "Manager, Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hero hero = db.Heroes.Find(id);
            if (hero == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "FirstName", hero.UserID);
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "City", hero.LocationID);
            ViewBag.SkillID = new SelectList(db.SkillLevels, "SkillID", "SkillName", hero.SkillID);
            return View(hero);
        }

        // POST: Heroes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Manager, Admin")]
        public ActionResult Edit([Bind(Include = "HeroID,UserID,Alias,FirstName,LastName,Description,IsActive,SkillID,LocationID,ImageFileName,Achievements")] Hero hero, HttpPostedFileBase ImageName)
        {
            if (ModelState.IsValid)
            {
                string savePath = Server.MapPath("~/Content/img/");
                string deletePath = (hero.ImageFileName);
                string oldImageName = hero.ImageFileName;
                string imageName = "";
                string oldExt = "";
                if (oldImageName != null)
                {
                    oldExt = oldImageName.Substring(oldImageName.LastIndexOf('.'));
                }
                if (hero.ImageFileName != null)
                {
                    imageName = ImageName.FileName;
                    string ext = imageName.Substring(imageName.LastIndexOf('.')).ToLower();
                    imageName = Guid.NewGuid() + ext;
                    string[] goodExts = { ".jpg", ".jpeg", ".png" };
                    if (goodExts.Contains(ext))
                    {
                        if (ext == oldExt)
                        {
                            ImageName.SaveAs(savePath + imageName);
                            hero.ImageFileName = imageName;
                        }
                        else
                        {
                            FileInfo file = new FileInfo(deletePath);
                            if (file.Exists)
                            {
                                file.Delete();
                            }
                            ImageName.SaveAs(savePath + imageName);
                            hero.ImageFileName = imageName;
                        }
                    }
                    else
                    {
                        return View();
                    }
                }
                else
                {
                    string fileName = "noImage.jpeg";
                    fileName = ImageName.FileName;
                    string ext = Path.GetExtension(ImageName.FileName).ToLower();
                    fileName = Guid.NewGuid() + ext;
                    string[] goodExts = { ".jpg", ".jpeg", ".png" };
                    if (goodExts.Contains(ext))
                    {
                        ImageName.SaveAs(savePath + fileName);
                        hero.ImageFileName = fileName;
                    }
                    else
                    {
                        fileName = "noImage.png";
                        hero.ImageFileName = fileName;
                    }
                }
                db.Entry(hero).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.AspNetUsers, "Id", "FirstName", hero.UserID);
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "City", hero.LocationID);
            ViewBag.SkillID = new SelectList(db.SkillLevels, "SkillID", "SkillName", hero.SkillID);
            return View(hero);
        }

        // GET: Heroes/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hero hero = db.Heroes.Find(id);
            if (hero == null)
            {
                return HttpNotFound();
            }
            return View(hero);
        }

        // POST: Heroes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Hero hero = db.Heroes.Find(id);
            db.Heroes.Remove(hero);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HeroBoard.MVC.UI/Views/Applications/Create.cshtml
@model HeroBoard.DATA.EF.Application

@if (User.IsInRole("Admin"))
{
    ViewBag.Title = "New Application";

    <div class="content-md">
        <h2 class="margin-t-40 margin-l-50p">Create</h2>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Application</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.OpenPositionID, "OpenPositionID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("OpenPositionID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.OpenPositionID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ApplicationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ApplicationDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ApplicationDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ManagerNotes, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ManagerNotes, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ManagerNotes, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IsDeclined, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.IsDeclined)
                            @Html.ValidationMessageFor(model => model.IsDeclined, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ResumeFileName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ResumeFileName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ResumeFileName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HeroBoard.MVC.UI/Views/Applications/Delete.cshtml
@model HeroBoard.DATA.EF.Application

@ViewBag.Title = "Delete";


<div class="content-xlg">
    <h2 class="margin-t-40 margin-l-50p">@ViewBag.Title</h2>

    <h3 class="margin-t-40 margin-l-25p">Are you sure you want to delete this?</h3>
    <div>
        <h4 class="margin-t-40 margin-l-25p">Application</h4>
        <hr />
        <dl class="dl-horizontal margin-l-15p">
            <dt>
                @Html.DisplayNameFor(model => model.ApplicationDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ApplicationDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ManagerNotes)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ManagerNotes)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.IsDeclined)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.IsDeclined)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ResumeFileName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ResumeFileName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.AspNetUser.FirstName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AspNetUser.FirstName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.OpenPosition.OpenPositionID)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.OpenPosition.OpenPositionID)
            </dd>

        </dl>

        <div class="margin-l-15p">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>
    </div>
</div>

HeroBoard.MVC.UI/Views/Applications/Details.cshtml
@model HeroBoard.DATA.EF.Application

@if (!User.IsInRole("Hero"))
{
    ViewBag.Title = "Details";

    <div class="content-md">
        <h2 class="margin-t-40 margin-l-50p">Details</h2>

        <div>
            <h4 class="margin-t-40 margin-l-50p">Application</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.ApplicationDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ApplicationDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ManagerNotes)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ManagerNotes)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.IsDeclined)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.IsDeclined)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ResumeFileName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ResumeFileName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.AspNetUser.FirstName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.AspNetUser.FirstName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.OpenPosition.OpenPositionID)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.OpenPosition.OpenPositionID)
                </dd>

            </dl>
        </div>
        <p>
            @if (!User.IsInRole("User"))
            {
                @Html.ActionLink("Edit", "Edit", new { id = Model.ApplicationID }) @:|
            }
            @Html.ActionLink("Return to Applications", "Index")
        </p>
    </div>
}

HeroBoard.MVC.UI/Views/Applications/Edit.cshtml
@model HeroBoard.DATA.EF.Application

@if (!User.IsInRole("Hero") && !User.IsInRole("User"))
{
    ViewBag.Title = "Edit";

<div class="content-md">
    <h2 class="margin-t-40 margin-l-50p">Edit</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Application</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ApplicationID)

            <div class="form-group">
                @Html.LabelFor(model => model.OpenPositionID, "OpenPositionID", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("OpenPositionID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.OpenPositionID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ApplicationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ApplicationDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ApplicationDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ManagerNotes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ManagerNotes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ManagerNotes, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsDeclined, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsDeclined)
                        @Html.ValidationMessageFor(model => model.IsDeclined, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ResumeFileName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.HiddenFor(model => model.ResumeFileName, new { htmlAttributes = new { @class = "form-control" } })
                    @if (Model.ResumeFileName != null)
                    {
                        <p>On-File</p>
                    }
                    else
                    {
                            <p>Not On Record</p>
                    }
                    @Html.ValidationMessageFor(model => model.ResumeFileName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HeroBoard.MVC.UI/Views/Applications/Index.cshtml
@model IEnumerable<HeroBoard.DATA.EF.Application>

@if (!User.IsInRole("Hero"))
{
    ViewBag.Title = "Open Applications";

    <div class="content-md">
        <h2 class="margin-t-40 margin-l-50p">Pending Applications</h2>
        <h3 class="margin-t-40 margin-l-50p">@TempData["message"]</h3>
        @if (User.IsInRole("Admin"))
        {
            <p class="margin-t-40 margin-l-25p">
                @Html.ActionLink("New Application", "Create")
            </p>
        }
        <table class="table margin-l-auto margin-r-auto">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ApplicationDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ManagerNotes)
                </th>
                <th>
                    Application Status
                </th>
                <th>
                    Resume
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AspNetUser.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OpenPosition.OpenPositionID)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ApplicationDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ManagerNotes)
                    </td>
                    @if (item.IsDeclined == null)
                    {
                        <td>
                            <p>Pending</p>
                            @if (User.IsInRole("Manager") || User.IsInRole("Admin"))
                            {

                                using (Html.BeginForm("HeroApplication", "Heroes", new { @id = @item.ApplicationID, @b = false }, FormMethod.Post, null))
                                {

                                    <input type="submit" value="Accept" class="btn btn-success" style="float: left;" />
                                }
                                @*<button>
                                       @Html.ActionLink("Approve", "HeroApplication", "Heroes",
                                      FormMethod.Post, new { id = item.ApplicationID, b = false,
                                          @class = "btn btn-default" })

                                    </button>*@
                            using (Html.BeginForm("AppReject", "Applications", new { @id = @item.ApplicationID, @b = true }, FormMethod.Post, null))
                            {

                                <input type="submit" value="Reject" class="btn btn-danger" />
                                }
                            }
                            @*<button>
                                    @Html.ActionLink("Decline", "Create", "Applications", FormMethod.Post, new { id = item.ApplicationID, b = false, @class = "btn btn-danger" })
                                </button>*@
                        </td>
                    }
                    @if (item.IsDeclined == false)
                    {
                        <td>
                            Approved
                        </td>
                    }
                    @if (item.IsDeclined == true)
                    {
                        <td>
                            Rejected
                        </td>
                    }

                    <td>
                        <a href="~/Content/Resumes/@item.ResumeFileName" download="@item.AspNetUser.FirstName @item.AspNetUser.LastName Resume">Download Resume</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AspNetUser.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OpenPosition.OpenPositionID)
                    </td>
                    <td>
                        @if (!User.IsInRole("User"))
                        {
                            @Html.ActionLink("Edit", "Edit", new { id = item.ApplicationID }) @:|
                            @Html.ActionLink("Details", "Details", new { id = item.ApplicationID }) @:|
                            @Html.ActionLink("Delete", "Delete", new { id = item.ApplicationID }, FormMethod.Post)
                        }
                    </td>
                </tr>
            }

        </table>
    </div>
}